[main_window]
width = 1400
height = 600
title = 'Subspace Constrained Particle Dynamics Simulation'

[panels]
side_width = 322
center_width = 756
parm_layout_column = 2

[spin]
decimals = 4

[graph]
quantity_graph_widgets = 2
axis_colors = [
    '#ff0000', 
    '#ff00ff', 
    '#00ff00', 
    '#00ffff', 
    '#0000ff', 
    '#ffff00'
]